name: Sync OpenAPI Documentation to ReadMe
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: 2G20LGXeio4aWitmvlBHifcrQtY16wcy:5febf83fdb77f394f3ed82ad
           
          # OPTIONAL CONFIG, use if necessary
          # oas-file-path: './swagger.json'
          # api-version: 'v1.0.0'
