# This is a basic workflow to help you get started with Actions

name: tests

env:
  NODE_ENV: testing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called tests, which runs unit and E2E tests
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
      
      - name: Create .testing.env for unit tests
        run: |
          echo -n "" > ./.testing.env;
          echo "MONGODB_URL=mongodb://localhost:27017/sanctuary" >> ./.testing.env;

      - name: Run unit tests
        run: npm run test

      - name: Recreate .testing.env for e2e tests
        run: |
          echo -n "" > ./.testing.env;
          echo "PORT=3003" >> ./.testing.env;
          echo "AUTH_PRIVATE_KEY=keyboard cat" >> ./.testing.env;
          echo "APP_URL=http://localhost:3003" >> ./.testing.env;
          echo "MONGODB_URL=mongodb://localhost:27017/sanctuary" >> ./.testing.env;
      
      # Removing E2E tests for now
      # - name: Run End-to-end tests
      #   run: npm run test:e2e
