# This is a basic workflow to help you get started with Actions

name: tests

env:
  NODE_ENV: testing

# Controls when the action will run.
on:
  push:
    branches:
      - main
      - develop

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called tests, which runs unit and E2E tests
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0

      - name: Create .testing.env for unit tests
        run: |
          echo -n "" > ./.testing.env;
          echo "MONGODB_URL=mongodb://localhost:27017/sanctuary-test" >> ./.testing.env;

      - name: Run unit tests
        env:
          BLOCKCHAIN_PROVIDER_URL: 'https://data-seed-prebsc-1-s1.binance.org:8545'
          REGISTRY_CONTRACT_ADDRESS: '0x8f98d3B5C911206C1Ac08B9938875620A03BCd59'
          ETH_BLOCKCHAIN_PROVIDER_URL: 'https://goerli.infura.io/v3/eb747af5515a4af7bd9003d821d04f5d'
          ETH_REGISTRY_CONTRACT_ADDRESS: '0x3F2254bc49d2d6e8422D71cB5384fB76005558A9'
          POLYGON_BLOCKCHAIN_PROVIDER_URL: 'https://polygon-mumbai.infura.io/v3/41367ca5932343298b672cd60fddc01d'
          POLYGON_REGISTRY_CONTRACT_ADDRESS: '0xaB61f05a9dabCEd63c9100b623A4c29FfD9bf077'
          AVALANCHE_BLOCKCHAIN_PROVIDER_URL: 'https://api.avax-test.network/ext/bc/C/rpc'
          AVALANCHE_REGISTRY_CONTRACT_ADDRESS: '0x65833489170A55374786B97C96e691949C60175a'
          ARBITRUM_BLOCKCHAIN_PROVIDER_URL: 'https://arbitrum-goerli.infura.io/v3/41367ca5932343298b672cd60fddc01d'
          ARBITRUM_REGISTRY_CONTRACT_ADDRESS: '0x97e8922eac4fa07e958667E3e7AEa7a7fe3eC9f6'
          SOLANA_BLOCKCHAIN_PROVIDER_URL: 'https://api.devnet.solana.com/'
          SOLANA_REPLICATOR_SECRET_KEY: ${{ secrets.SOLANA_REPLICATOR_SECRET_KEY }}
          SOLANA_CHAIN_PROGRAM_ID: '4SPgs3L7Ey9VyRuZwx4X3y86LSAZXP2Hhpz9Sps4v3iT'
        run: npm run test

      - name: Run End-to-end tests
        env:
          BLOCKCHAIN_PROVIDER_URL: 'https://data-seed-prebsc-1-s1.binance.org:8545'
          REGISTRY_CONTRACT_ADDRESS: '0x8f98d3B5C911206C1Ac08B9938875620A03BCd59'
          ETH_BLOCKCHAIN_PROVIDER_URL: 'https://goerli.infura.io/v3/eb747af5515a4af7bd9003d821d04f5d'
          ETH_REGISTRY_CONTRACT_ADDRESS: '0x3F2254bc49d2d6e8422D71cB5384fB76005558A9'
          POLYGON_BLOCKCHAIN_PROVIDER_URL: 'https://polygon-mumbai.infura.io/v3/41367ca5932343298b672cd60fddc01d'
          POLYGON_REGISTRY_CONTRACT_ADDRESS: '0xaB61f05a9dabCEd63c9100b623A4c29FfD9bf077'
          AVALANCHE_BLOCKCHAIN_PROVIDER_URL: 'https://api.avax-test.network/ext/bc/C/rpc'
          AVALANCHE_REGISTRY_CONTRACT_ADDRESS: '0x65833489170A55374786B97C96e691949C60175a'
          ARBITRUM_BLOCKCHAIN_PROVIDER_URL: 'https://rinkeby.arbitrum.io/rpc'
          ARBITRUM_REGISTRY_CONTRACT_ADDRESS: '0x97e8922eac4fa07e958667E3e7AEa7a7fe3eC9f6'
          SOLANA_BLOCKCHAIN_PROVIDER_URL: 'https://api.devnet.solana.com/'
          SOLANA_REPLICATOR_SECRET_KEY: ${{ secrets.SOLANA_REPLICATOR_SECRET_KEY }}
          SOLANA_CHAIN_PROGRAM_ID: '4SPgs3L7Ey9VyRuZwx4X3y86LSAZXP2Hhpz9Sps4v3iT'
        run: npm run test:e2e
  remote_tests:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Call Reff App Test for Develop
        run: |
          curl -X POST https://api.github.com/repos/umbrella-network/babel/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u 'umb-dev:${{ secrets.BOT_GITHUB_TOKEN }}' \
          --data '{"event_type": "Reff_App_Test_Develop", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: Call SDK Test for Develop
        run: |
          curl -X POST https://api.github.com/repos/umbrella-network/canvas/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u 'umb-dev:${{ secrets.BOT_GITHUB_TOKEN }}' \
          --data '{"event_type": "SDK_Test_Develop", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
